<a href="https://colab.research.google.com/github/Shranobxtha/MathWorkshop/blob/main/workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part1:
Problem 1: Create a 2D ndarray of type Integer, e.g., �
1 2 3
4 5 6
7 8 9
� and see its properties.

In [ ]:
import numpy as np
if __name__=="__main__":
  arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
  print("Array =")
  print(arr)
  print("Data Type of the Array                                     =", arr.dtype)
  print("Number of dimensions of the Array                          =", arr.ndim)
  print("Shape of the Array                                         =", arr.shape)
  print("Size of the Array                                          =", arr.size)
  print("Number of bytes used by each element of the Array          =", arr.itemsize)
  print("Total bytes used by the Array                              =", arr.nbytes)
  print("Memory Layout information                                  =", arr.flags)


Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array                                     = float64
Number of dimensions of the Array                          = 2
Shape of the Array                                         = (3, 3)
Size of the Array                                          = 9
Number of bytes used by each element of the Array          = 8
Total bytes used by the Array                              = 72
Memory Layout information                                  =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Problem 2: Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print
the matrix.

In [ ]:
arr2 = 3 * np.ones((4,5), dtype=float)
print("Array = ")
print(arr2)
print("Shape = ", arr2.shape)
print("DataType = ", arr2.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


Problem 3: What is the other way to create the same matrix as above?

In [ ]:
arr3 = np.full((4, 5), 3.0)
print("Array =")
print(arr3)
print("Shape = ", arr3.shape)
print("DataType = ", arr3.dtype)

Array =
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


Problem 4: Construct a matrix �𝑎𝑎𝑖𝑖𝑖𝑖 � of shape (3,3) whose elements are given by 𝑎𝑎𝑖𝑖𝑖𝑖 = 1
2 |𝑖𝑖 − 3𝑗𝑗|.

In [ ]:
arr4 = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3, 3), dtype=int)
print("Array = ")
print(arr4)
print("Shape = ", arr4.shape)
print("DataType = ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape =  (3, 3)
DataType =  float64


Problem 5: Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4].

In [ ]:
diag_elements = [1, 2, 3, 4]
arr5 = np.diag(diag_elements)
print("Array =")
print(arr5)
print("Shape = ", arr5.shape)
print("DataType = ", arr5.dtype)

Array =
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Shape =  (4, 4)
DataType =  int64


Problem 6: Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain
a matrix of shape (3,3) that contains only upper-left portion of the original matrix.

In [ ]:
arr6 = np.random.randint(1, 10, (4, 5))
print("Original (4,5) Matrix:")
print(arr6)
sliced_arr = arr6[0:3, 0:3]
print("\nSliced (3,3) Upper-Left Matrix:")
print(sliced_arr)
print("\nShape of sliced matrix =", sliced_arr.shape)

Original (4,5) Matrix:
[[7 9 4 5 7]
 [4 8 8 5 8]
 [2 5 5 5 4]
 [6 4 9 6 5]]

Sliced (3,3) Upper-Left Matrix:
[[7 9 4]
 [4 8 8]
 [2 5 5]]

Shape of sliced matrix = (3, 3)


Part2:
Problem 1: Create two matrices 𝑨𝑨 = �
1 2 3
4 5 6
7 8 9
� and 𝑩𝑩 = �1 1 1
2 2 2�. Add them together. What
do you observe? Give the explanation behind it.

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[1, 2, 2]])
result = A + B
print("Matrix A (3x3):")
print(A)
print("\nMatrix B (1x3):")
print(B)
print("\nResult (A + B):")
print(result)

Matrix A (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B (1x3):
[[1 2 2]]

Result (A + B):
[[ 2  4  5]
 [ 5  7  8]
 [ 8 10 11]]


Problem 2: Given a matrix and a vector, write a Python function that performs Matrix-Vector
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [ ]:
def dot_product(vec1, vec2):
    # flatten the intput vectors
    vec1 = vec1.flatten()
    vec2 = vec2.flatten()
    return np.sum(np.multiply(vec1, vec2))

def matrix_vector_product(mat, vec):
    m,n = mat.shape
    p,q = vec.shape

    assert n == p, "the matrix and vector are not compatible for multiplication!"

    # create a ndarray to store the result
    result = np.zeros((m,q), dtype=float)

    # Loop to perform Matrix-Vector product
    # Perform dot product between the vector and each row of the matrix
    for i in range(m):
        result[i] = dot_product(mat[i,:], vec)

    return result

if __name__ == "__main__":

    """ Part 2: Problem 2: Given a matrix and a vector, write a function that
    performs Matrix-Vector product. """
    mat1 = np.full((3,3), 3, dtype=int)
    vec1 = np.full((3,1), 2, dtype=int)
    print("Matrix = ")
    print(mat1)
    print("Vector = ")
    print(vec1)

    # Call the function matrix_vector_product(mat, vec)
    result1 = matrix_vector_product(mat1, vec1)
    print("Result = ")
    print(result1)

    # Check with numpy in-built function for multiplication
    result2 = mat1 @ vec1
    print("Result = ")
    print(result2)

Matrix = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
[[2]
 [2]
 [2]]
Result = 
[[18.]
 [18.]
 [18.]]
Result = 
[[18]
 [18]
 [18]]


Problem 3: Given two compatible matrices, write a Python function that performs Matrix-Matrix
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [ ]:
import numpy as np

def dot_product(vec1, vec2):
    # flatten the input vectors to ensure they are 1D
    v1 = vec1.flatten()
    v2 = vec2.flatten()
    return np.sum(np.multiply(v1, v2))

def matrix_matrix_product(mat1, mat2):
    m, n = mat1.shape
    p, q = mat2.shape

    # Check compatibility: Columns of mat1 must equal rows of mat2
    assert n == p, "Matrices are not compatible for multiplication!"

    # Create a result matrix of shape (m, q)
    result = np.zeros((m, q), dtype=float)

    # Loop through each row of the first matrix (m)
    for i in range(m):
        # Loop through each column of the second matrix (q)
        for j in range(q):
            # The element at result[i, j] is the dot product of:
            # Row i from mat1 and Column j from mat2
            result[i, j] = dot_product(mat1[i, :], mat2[:, j])

    return result

if __name__ == "__main__":
    # Create two compatible matrices
    # A is (2, 3), B is (3, 2) -> Result will be (2, 2)
    A = np.array([[1, 2, 3],
                  [4, 5, 6]])

    B = np.array([[7, 8],
                  [9, 1],
                  [2, 3]])

    print("Matrix A:")
    print(A)
    print("\nMatrix B:")
    print(B)

    # Manual Multiplication
    res_manual = matrix_matrix_product(A, B)
    print("\nResult (Manual Function):")
    print(res_manual)

    # NumPy Built-in Multiplication (using @ operator or np.matmul)
    res_numpy = A @ B
    print("\nResult (NumPy built-in @):")
    print(res_numpy)

    # Verify results are the same
    print("\nVerification (Arrays Match):", np.allclose(res_manual, res_numpy))

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[7 8]
 [9 1]
 [2 3]]

Result (Manual Function):
[[31. 19.]
 [85. 55.]]

Result (NumPy built-in @):
[[31 19]
 [85 55]]

Verification (Arrays Match): True


Problem 4: Given a matrix, write a Python function that checks if it is a symmetric matrix.

In [ ]:
import numpy as np

def is_symmetric(mat):
    # Step 1: Check if the matrix is square
    # A symmetric matrix must have the same number of rows and columns
    m, n = mat.shape
    if m != n:
        return False

    # Step 2: Compute the transpose
    # In NumPy, you can use mat.T or np.transpose(mat)
    mat_transpose = mat.T

    # Step 3: Compare the original matrix with its transpose
    # np.array_equal checks if shapes and elements are identical
    return np.array_equal(mat, mat_transpose)

if __name__ == "__main__":
    # Example 1: A symmetric matrix
    A = np.array([[1, 2, 3],
                  [2, 4, 5],
                  [3, 5, 6]])

    # Example 2: A non-symmetric matrix
    B = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

    print("Matrix A is symmetric:", is_symmetric(A))
    print("Matrix B is symmetric:", is_symmetric(B))

Matrix A is symmetric: True
Matrix B is symmetric: False
